version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=pass
    ports:
      - "5432:5432"
    volumes: 
      - ./db-data:/var/lib/postgresql/data

  backend:
    image: "turkogluc/backend"
    container_name: "backend"
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: "turkogluc/frontend"
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend
